# Site settings
title: Fleeg
email: lucasboscaini@gmail.com
url: https://fleeg.github.io
description: "Fleeg: Opensource Social Platform in construction."
keywords: "Opensource, Social Network, Platform"
skills: "Opensource Social Platform <br/> [Under Construction]"
meta_author:

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Fleeg Project
  location: Origins
  social: Join Us
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/fleeg
  - title: slack
    url: https://fleeg.slack.com
  - title: twitter
    url: https://twitter.com/lucasboscaini

# Postal address (add as many lines as necessary)
address:
  - line: Written from scratch by
  - line: <a href="https://github.com/lucasb">Lucas Boscaini</a>.

# Credits content
credits: 'All rights reserved. Made with <br/> <a href="https://jekyllrb.com/">Jekyll</a> and hosted by <a href="https://github.com/fleeg">GitHub</a>.'

# Build settings
markdown: kramdown
permalink: pretty
